title: <p align="center"> Naga Shanmukha </p>
logo: /assets/img/logo.png
description: 
  <p align="center">
  <a href="https://github.com/naga-shanmukha">GitHub</a>
  <br>   
  I'm working on Data Science & Machine learning related problems.
  <br>
  </p>
theme: jekyll-theme-minimal

